### ISSUE TITLE
Get feedback from Vimium developers

### ISSUE THREAD

**Issue by lydell** [lydell/webextension-keyboard#2]
@philc @smblott-github @mrmr1993 @gdh1995 I’m shamlessly pinging you here. Here’s the summary:

1. There is a Vimium-like add-on for Firefox called [VimFx](https://github.com/akhodakivskiy/VimFx/).
2. Firefox nowadays support Chrome’s extension API. They call it “WebExtensions.”
3. Firefox is planned to stop supporting all “legacy” types of Firefox add-ons (including VimFx) at the end of 2017.
4. I’m the developer of VimFx. I need to convert VimFx into a WebExtension, without losing too much of VimFx’s functionality.
5. Therefore, I’m proposing a few new APIs.
6. If Firefox implements these new APIs, Chrome might as well.
7. If Chrome also implements them, I want to be sure that Vimium will find them useful as well.

So, if you have the time, it’d be great if you’d read through the README of this repo and see what you think! If you don’t have the time, that’s fine – sorry for bothering you! Thanks for Vimium!

**Since this issue has become a bit long, please open a new issue!**

**Comment by gdh1995** [comment]
Well, thanks for your invitation, but I know little about Firefox's limits to web extensions, so if I'm saying anything wrong, please figure out it.

## browser.keyboard

You want a method to receive all keyboard events, which will surely be too expensive to tolerate. There're so many disadvantages that I do not expect it will come true:

Obviously, It requires real-time cross-process communication, which means much time and CPU cost.

What's more important is, the background page can not know what to do easily.
* Up to now, only the content script of Vimium is able to know `isEditable(document.activeElement)` and decide if `InsertMode` is enabled, while a background page (which is in another process) knows nothing. 
* But the listener for `onKey` must know whether a plain key event (a printable char?) should be suppressed.
  * Will you send all status changes of something like `InsertMode` to backend? If so, it's also too heavy.
  * How does an extension know where's the current focus? On the page, the location bar, or the main menu?
  * An extra API to access these info? But because most of Chrome/WebExtension APIs are asynchronous, we can not ensure the background process always knows the lastest status.
* Modern listeners for `window` must return at once - the new feature of async listeners seems not so good.

My suggestion is splitting this API by context:
* Use `keyboard.locationBar` to handle all keyboard events if the location Bar is focused.
* Use `keyboard.findBar` if someone is searching.
* As for HTML page, an extension MUST grab key events using normal `window.addEventListener`, because there're so many things to check.

For those pages where content script is disallowed, and some toolbars where no place to input, I think a listener which might suppress printable keys would be annoying (and useless), while a loosened `command.onCommand` should be better.

There're other problems, such as:
* Different priorities if more than one extension requires the `keyboard` permission and installs listeners.
* How the browser will tolerate a timeout? I have no idea.

## browser.keyboardShortcutActions

It's indeed useful but might not enough compatible among different browsers. More options are needed.

**Comment by lydell** [comment]
@gdh1995 Thanks for your feedback! :+1:

First, one very important point: the proposed `browser.keyboard.onKey` API is almost exactly how VimFx works today. Let me elaborate:

VimFx is a so-called "bootstrapped" extension. That means that there's a single file called `bootstrap.js`, which is like a background script in a WebExtension. "Frame scripts" can be loaded into web pages, which are like WebExtension content scripts. All of these scripts live in different processes and can only talk to each other via message passing.

In `bootstrap.js`, VimFx basically have one single big 'keydown' listener, which drives the entire extension.

In the frame scripts, VimFx listens for 'focus' and 'blur' events, and sends messages back to `bootstrap.js`, telling the type of the currently focused element. This lets `bootstrap.js`:

- Change the color of VimFx's toolbar button (it turns grey when a text input is focused).
- Know if it should pass a `t` key press along to the webpage (so that it appears as text in some text input), or treat it as the command to open a new tab, for example.

This works great. (In VimFx, `bootstrap.js` is the "master", and only as little logic as possible is run in the frame scripts. The frame scripts send back data to `bootstrap.js` as soon as they can.)

---

> Obviously, It requires real-time cross-process communication, which means much time and CPU cost.

Sorry, this is not obvious to me. Do you mean that the UI of the browser runs in one process, and the background scripts of a WebExtension in another? I guess that's a fair point. But I don't see the trouble either. Let's say that the use presses CTRL+T to open a new tab. I don't think that a WebExtension with an `onKey` handler can slow down things so much that the CTRL+T shortcut feels sluggish?

> Up to now, only the content script of Vimium is able to know isEditable(document.activeElement) and decide if InsertMode is enabled, while a background page (which is in another process) knows nothing.
> But the listener for onKey must know whether a plain key event (a printable char?) should be suppressed.
> Will you send all status changes of something like InsertMode to backend? If so, it's also too heavy.

See my explaination of how VimFx works today. This is not a problem.

> How does an extension know where's the current focus? On the page, the location bar, or the main menu?

It doesn't need to. `onKey` listeners won't fire at all if the location bar, the main menu (which typically has "access keys") or any other UI element that can receive text input has focus.

> Modern listeners for window must return at once - the new feature of async listeners seems not so good.

Sorry, I don't quite follow along here. Mind clarifying? :)

> Use keyboard.locationBar to handle all keyboard events if the location Bar is focused.
> Use keyboard.findBar if someone is searching.

My idea is that if the location bar or the find bar (or any UI element that can receive text input) is focused, WebExtensions can't do anything at all. (See above.) So, no need for these APIs.

> As for HTML page, an extension MUST grab key events using normal window.addEventListener, because there're so many things to check.

Sorry, I don't quite follow along here. Mind clarifying? :)

Remember, VimFx does _not_ listen for 'keydown' events in frame/content scripts today, and it works just fine.

What are examples of the many things to check?

> For those pages where content script is disallowed, and some toolbars where no place to input, I think a listener which might suppress printable keys would be annoying (and useless), while a loosened command.onCommand should be better.

Sorry, I don't quite follow along here. Mind clarifying? :)

Are you talking about pages like chrome://extensions? What toolbars?

Regarding "suppressing printable keys", my idea is that pages such as `chrome://extensions` are treated as part of all other browser UI, which means that `onKey` listeners won't run at all if an element which can receive text input is focused.

> Different priorities if more than one extension requires the keyboard permission and installs listeners.

Today, it is very much possible that several extensions use the 'keydown' listening method in `bootstrap.js` that VimFx uses. However, we've had zero issues regarding conflicts with other extensions when it comes to keyboard handling. I think that the only way conflicts can arise is if the user installs VimFx and Vimperator at the same time and expects that to work. Of course it won't, and people don't expect that in reality either.

> How the browser will tolerate a timeout? I have no idea.

Sorry, I don't understand this bit. What timeout?

> browser.keyboardShortcutActions: It's indeed useful but might not enough compatible among different browsers. More options are needed.

I don't think compatibility is much of a concern. We might end up with code like this, but I think it's fine:

```js
function command_focusLocationBar() {
  if (browser.keyboardShortcutActions.selectLocationBar) {
    // Firefox.
    browser.keyboardShortcutActions.selectLocationBar()
  } else if (browser.keyboardShortcutActions.focusLocationBar) {
    // Chrome.
    browser.keyboardShortcutActions.focusLocationBar()
  } else {
    notifyUser('Your browser does not support focusing the location bar.')
  }
}
```

Also, what do you mean by "More options are needed"?

---

Again, thanks for your feedback. Don't get me wrong above: I'm not angry with you or trying to pick on you or anything like that (in case my responses made that impression). ☮️

**Comment by lydell** [comment]
>  It requires real-time cross-process communication, which means much time and CPU cost.

Thinking about this some more: All browser keyboard shortcuts are already dependent on the execution of JavaScript in web pages, because of `event.preventDefault()`.

**Comment by gdh1995** [comment]
Sorry I know too little about Firefox addons. The main mistake I've made is that Firefox has only single process and there's less problems.

Today I have some work to do and I'll learn more and give my new thinking in about ten hours.

**Comment by lydell** [comment]
Nope, Firefox has multiple processes – it's just not enabled for everyone yet. VimFx is already written in a multi-process aware way, and works just fine when multi-process is enabled in Firefox.

There is no need to know anything specific about Firefox. "Everything" I've written should be true for Chrome as well.

**Comment by gdh1995** [comment]
Well, I tried Firefox's Debugger for a while, and confirmed that the VimFx works just inner the main thread of Firefox and is able to access all of Firefox's inner functionalities and status (like `window.gBrowser.selectedBrowser`), all of content page's `window` objects (if I didn't misunderstand), and all events.

It's indeed cheap to pass all events and amounts of messages to the current JavaScript environment of VimFx. But the standard multi-process environment of `WebExtension` has no such a convenience.

On Chrome, the `background.html` of `Vimium` can not access any JavaScript/DOM objects of those web pages, and it‘s only permitted to send requests to `chrome` and content script environments asynchronously. The internal implementation uses JSON text to transport messages across processes, so it's CPU-costly and those DOM objects can not be passed. 
* Once `Vimium` made its logging action too slow and it got stuck on special Google Docs page (https://github.com/philc/vimium/issues/2134).

Although we can still pass each change about `doc.activeElement` from `*-frame.coffee` to `main.coffee`, it's not a good practice.

My ideas about `keyboard.findBar` is mainly for support customized (control) key bindings, such as pressing `Up` or `Down` to switch among one's find history (this is what `Vimium` does in its `FindMode` HUD).

**Comment by lydell** [comment]
Yes, Firefox can still access web page content from the main thread (through `window.gBrowser.selectedBrower.etc`), but that works via _compatibility shims,_ and is only intended to make old add-ons that haven't been updated for multi-process work. That's just a temporary measure, that will eventually be removed. Firefox add-on developers are strongly encouraged to only use the newer, multi-process APIs (because the shims have very bad performance). VimFx uses only multi-process-friendly APIs, which is very similar to how WebExtensions work.

> On Chrome, the background.html of Vimium can not access any JavaScript/DOM objects of those web pages, and it‘s only permitted to send requests to chrome and content script environments asynchronously.

VimFx does not access web page content from the main thread, and only uses asynchronous messaging between bootstrap.js (background script) and frame scripts (content scripts), as mentioned above.

> The internal implementation uses JSON text to transport messages across processes, so it's CPU-costly and those DOM objects can not be passed.

Of course the DOM objects cannot be passed – not even in Firefox. VimFx examines `document.activeElement` in the frame script, and then sends just the _type_ of element back to bootstrap.js (VimFx uses these types: `'editable'`, `'activatable'`, `'adjustable'`, `'ignore'` and `'none'`).

- VimFx only sends _small_ payloads.
- The payloads are not sent very often. Focus and blur events only happen occasionally – it's not like one message is sent per second, or something like that.

So I can't see how this affects performance. If it would, someone of VimFx's ~18k users surely must have reported any slowness by now? (VimFx has used this architecture for more than a year.)

> Although we can still pass each change about `doc.activeElement` from `*-frame.coffee` to `main.coffee`, it's not a good practice.

I'd argue the opposite: It's very good to centralize as much logic and state as possible in one place.

> `keyboard.findBar`

If you want to talk more about additional proposals like `keyboard.findBar`, please open a separate issue.

**Comment by gdh1995** [comment]
Oh I had a new misunderstanding. In my tests, `VimFx`'s "background" is able to see some `<tabbrowser>` objects representing some pages. I once thought they allows `VimFx` to access inner DOM nodes, but in fact they don't.

Then according to what you said, VimFx has proved that a global JS key listener is OKay, but I still have doubts:

> Yes, Firefox can still access web page content from the main thread (through window.gBrowser.selectedBrower.etc), but that works via compatibility shims ... (because the shims have very bad performance).

I find https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Cross_Process_Object_Wrappers, and I think we have agreed that this method is expensive, haven't we?

> VimFx uses only multi-process-friendly APIs

However, according to
https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Limitations_of_chrome_scripts#DOM_Events,
FireFox currently supports `frame.addEventListener` in the "Chrome" process by a shim, too:
> The shim intercepts chrome process code that adds listeners to XUL elements and sets up listeners in the content process, relaying the result back to the chrome process. The Event object itself is relayed to the chrome process as a CPOW.

I'm not sure whether this shim itself depends on `CPOW`, but because `VimFx`'s `extension/lib/events.coffee` calls `utils.listen` and it needs an `event` object to call `suppressEvent`, and this action needs to be send back its content process, I think your `onKey` is just the same as it.

Therefore, considering Firefox has written such a shim, its costs seems tolerable. I have no more objection to an `onKey`, but nor approval.

**Comment by lydell** [comment]
Yes, the shims use "Cross Process Object Wrappers", which are slow, and yes, we agree that they are expensive. But I don't understand why this motivates "but I still have doubts"? They have nothing to do with the WebExtension proposals in this repo: They are not needed to implement the proposed APIs, and VimFx does not use them today.

> `addEventListener` in the "Chrome" process ... CPOW

Firefox add-ons can declare in a manifest file that they are fully multi-process compatible. VimFx does so. If you do, no shims will be activated. None at all. VimFx runs `chromeWindow.addEventListener('keydown', event => {}, true)` in the main/background/bootstrap.js thread. If such a listener fires due to typing in a text input in a web page, `event.target` won't be the `<input>` element that was focused. It will be the XUL `<browser>` element that contains the web page. No CPOWs. Because VimFx has declared that it doesn't want any expensive shims.

> I have no more objection to an `onKey`, but nor approval.

Then lets end the discussion here.

**Comment by philc** [comment]
@lydell Hey Simon, I wanted to discuss an idea for firefox with you. FYI I sent you an email at the gmail listed in your [npm profile](https://www.npmjs.com/~lydell) but wasn't sure if you're checking that address.

**Comment by lydell** [comment]
@philc Yes, I got your email. I'll get back to you soon :)

**Comment by lydell** [comment]
Closing since I've decided to abandon the project. See the readme for more information.
