### ISSUE TITLE
Explain how to handle multi-stroke key shortcuts (such as an Emacs mode might use)

### ISSUE THREAD

**Issue by ncalexan** [lydell/webextension-keyboard#3]
Hi!  This is looking really great, but I'd like to have the proposal spell out how an Emacs mode might handle multi-stroke shortcuts like `C-x C-c` or `C-u C-x 1` or similar.

Would one have to bind `C-x` and then dynamically bind `C-c` until after keyboard input was complete?  Or could the system handle such multi-stroke shortcuts in the definition of "key spec", which I didn't see?

Apologies if I overlooked this in the existing document; I was reading quickly.

**Comment by lydell** [comment]
At first you’d add an `onKey` listener for `C-x` and `C-u`.

- If the user presses `C-x`, remove all `onKey` listeners and add `C-c`.
  - If the user presses `C-c`, remove all `onKey` listeners, run some action and add back `C-x` and `C-u`.
- If the user presses `C-u`, remove all `onKey` listeners and add `C-x`.
  - If the user presses `C-x`, remove all `onKey` listeners and add `1`.
    - If the user presses `1`, remove all `onKey` listeners, run some action and add back `C-x` and `C-u`.

Does that makes sense?

---

Actually, it was really good that you asked, because it made me realized that I’ve overlooked one thing from VimFx.

Let’s say that you added `C-x C-c` as a shortcut for a VimFx command. If you then press `C-x C-a` (which doesn’t exist), VimFx will suppress the event (so that the Firefox shortcut `C-a` isn’t triggered, and the web page doesn’t receive the 'keydown' event), and the return to the “top level” (adding back `C-x` and `C-u`). This is not possible with my proposed APIs; instead, the Firefox shortcut `C-a` (select all text) would be triggered, and you would be able to press `C-x C-a C-c` to trigger the `C-x C-c` command (with the side-effect of selecting all text). Need to think about that.

**Comment by ncalexan** [comment]
On Fri, Jan 6, 2017 at 9:41 AM, Simon Lydell <notifications@github.com>
wrote:

> At first you’d add an onKey listener for C-x and C-u.
>
>    - If the user presses C-x, remove all onKey listeners and add C-c.
>       - If the user presses C-c, remove all onKey listeners, run some
>       action and add back C-x and C-u.
>    - If the user presses C-u, remove all onKey listeners and add C-x.
>       - If the user presses C-x, remove all onKey listeners and add 1.
>          - If the user presses 1, remove all onKey listeners, run some
>          action and add back C-x and C-u.
>
> Does that makes sense?
>
Yes, this is what I expected.  My expectation, not based on experience but
on reading code from other systems that try to do Emacs-style key handling,
is that this will be very difficult for an extension to get right.  It
might be worth trying to make Firefox do more of the multi-stroke heavy
lifting.  (As you note below.)


> ------------------------------
>
> Actually, it was really good that you asked, because it made me realized
> that I’ve overlooked one thing from VimFx.
>
The system works!  \o/

**Comment by lydell** [comment]
> this will be very difficult for an extension to get right. It might be worth trying to make Firefox do more of the multi-stroke heavy lifting. 

I agree that it is difficult to get right, but not that Firefox should do more heavy lifting. The difficult parts should be in the add-on, where things are easy to change. Firefox should be low-level enough to provide the things needed to implement different keyboard shortcut systems.

I’ve updated the proposal. Now, it looks like this: `browser.keyboard.onKey.addListener(listener, options = {})`, which is more similar to `window.addEventListener('keydown', event => {})` in a web page. No need to add and remove listeners after each key press anymore, and it is now possible to suppress every key press in the middle of a multi-key shortcut.

**Comment by cmcaine** [comment]
@ncalexan, would you be willing to comment on [this](https://github.com/lydell/webextension-keyboard/issues/1#issuecomment-292230434)?
